name: Generate Contribution Snake

# Runs hourly (change schedule as you prefer)
on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours; change if you want
  workflow_dispatch:        # allows manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # the profile repo (the README repository)
          fetch-depth: 0

      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.3.0
        with:
             github_user_name: ${{ github.repository_owner }}
             output-file: ./snake/snake.gif
             output-format: svg
             username: ${{ github.repository_owner }}


         

      - name: Commit generated animation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # create folder if necessary
          mkdir -p snake
          git add snake/snake.gif
          # if no changes, this will fail; handle gracefully
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update contribution snake animation"
            git push origin HEAD:main
          fi
